feat: add installation script
arl/gitmux pull request #120
Opened 2024-06-09 21:19 UTC by Chaitanyabsprip

## Purpose
There should be an easy way to automate installation of gitmux.
#104 

## Approach
Currently I've in-lined all dependencies from my scripts and found an alternative method of extracting latest version from Github api instead of using jq.

2024-06-09 21:20 UTC, Chaitanyabsprip commented
I'm not sure how the version argument can be respected when downloading from a package manager. I haven't added choice of version if the package is being installed from a package manager. I would suggest dropping that part of the script and relying only on curl and github api.

2024-06-09 21:22 UTC, Chaitanyabsprip commented
There needs to be a discussion about what the default installation directory will be. Currently I've kept it as `$HOME/.local/bin`

2024-06-09 21:55 UTC, arl requested changes
> I'm not sure how the version argument can be respected when downloading from a package manager. I haven't added choice of version if the package is being installed from a package manager. I would suggest dropping that part of the script and relying only on curl and github api.

I think we should refine and limit the scope of the script. I expect the script to be used by people that wants to automate installation for their dot files, not to install gitmux for any package manager/distro out there.

In that case, the user already knows the os and architecture they need, these should be passed as arguments to the script.

As for the version number, for a first version of the script I'd say we can also pass it as parameter, and refine later.



> There needs to be a discussion about what the default installation directory will be. Currently I've kept it as `$HOME/.local/bin`

I think this should also be passed as parameter to the script.

To sum it up: we should keep it very simple:
 - check that all parameters are passed
 - check that dependency exist (curl or wget, jq)

This should be already helpful for most people.
And it'd be a good base if more features/automation is needed later.

2024-06-09 21:55 UTC, arl commented on install
> +go_install() { :; }
Not needed

2024-06-09 21:55 UTC, arl commented on install
> +pkg_install() {
Not needed

2024-06-09 21:55 UTC, arl commented on install
> +success() { printf " \033[1;32m ✔ %s\033[0m\n" "$*"; }
Pretty printing/formatting not needed for this script.
We should give a clear error message and exit 1 or 0 based on the final outcome

2024-06-09 21:55 UTC, arl commented on install
> +distro() {
out of scope

2024-06-09 21:55 UTC, arl commented on install
> +gh_install() {
this is the part we need

2024-06-09 22:36 UTC, Chaitanyabsprip commented
I've made the requested changes.

2025-08-11 07:11 UTC, arl approved these changes
Sorry for the long time it took me.
That looks good as a first step towards providing a one-liner install like many projects. 

In a next PR, I'd like to add a GitHub action that runs your script for 2 prominent os/arch pairs, after release creation, so we can be confident to propose this directly in the readme.

Thanks a lot @Chaitanyabsprip

2025-08-11 07:13 UTC, arl commented
Sorry can you rename the file to `install.sh` ?

2025-08-11 07:33 UTC, chaitanyabsprip commented
updated

2025-08-11 07:41 UTC, arl approved these changes
LGTM!

2025-08-11 07:41 UTC, merged